bases:
- ../../base

patches:

- target:
    kind: Deployment
    name: my-app
  patch: |-
    - op: remove
      path: /spec/template/spec/containers/0/args
    - op: add
      path: /spec/template/spec/containers/0/args
      value: 
          - "-text=version 1-1-0"

- target:
    kind: Service
    name: my-app-svc
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30100